<?php
namespace ThemeCheck;

class Artisteer_Checker extends CheckPart
{	
		public function doCheck( $php_files, $css_files, $other_files)
    {
        $this->errorLevel = ERRORLEVEL_SUCCESS;
        // combine all the php files into one string to make it easier to search
        $php = implode( ' ', $php_files );
        
				foreach ( $this->code as $key )
				{
					if (strpos( $php, $key ) !== false)
					{
						$this->messages[] = __all('Typical Artisteer code was found.', $key);
            $this->errorLevel = $this->threatLevel;
						break;
					}
				}
    }
}

class Artisteer extends Check
{	
    protected function createChecks()
    {
			$this->title = __all("Artisteer theme");
			$this->checks = array(
						new Artisteer_Checker('ARTISTEER', TT_COMMON, ERRORLEVEL_WARNING, __all("Autogenerated theme"), 
																																					 array ("art_normalize_widget_style_tokens",
																																									"art_include_lib",
																																									'_remove_last_slash($url) {',
																																									"adi_normalize_widget_style_tokens",
																																									"m_normalize_widget_style_tokens",
																																									"bw = '<!--- BEGIN Widget --->';",
																																									"ew = '<!-- end_widget -->';",
																																									"end_widget' => '<!-- end_widget -->'") , 'ut_artisteer.zip')
			);
    }
}